### PR TITLE
updated docker part

### PR DESCRIPTION
**Pull request by mitjajez**
Docker build fixed, time to fix django - I need help here

### CODE REVIEW

**Comment by mitjajez** [comment]
I'd also split nginx into it's own separate docker container

**Comment by mitar** [comment]
I would prefer using tozd base image.

**Comment by mitjajez** [comment]
So https://github.com/tozd/docker-postgresql and https://github.com/tozd/docker-nginx
I can try with those ..
What about updating those docker images since they are not official?

**Comment by mitar** [comment]
I think we should first get this to run with old versions. And then we can start updating them to the latest versions. I was also planing to update those images anyway, so I can look into that.

**Comment by mitjajez** [comment]
using "image: docker-postgresql:9.6" instead of "postgres:9.6" in docker-compose.yaml
cause error:
ERROR: pull access denied for docker-postgresql, repository does not exist or may require 'docker login'

**Comment by mitjajez** [comment]
`docker-compose up` return
```
app_1  | bash: cannot set terminal process group (-1): Inappropriate ioctl for device
app_1  | bash: no job control in this shell
```
it continue
but ended in [scripts/migrate.py#L13](https://github.com/mitjajez/mainpage/blob/05037ce56060ae32fa4e2441791b0c4b3c965631/scripts/migrate.py#L13)
`python manage.py syncdb --noinput`
with error:
`django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet`

How to get out witch app isn't loaded yet? Should i go over [INSTALLED_APPS](https://github.com/mitjajez/mainpage/blob/05037ce56060ae32fa4e2441791b0c4b3c965631/mainpage/settings.py#L202) in settings.py uncommenting one by one?

**Comment by rasovica** [comment]
Look at my pr #7  I think I got a few steps further, I think I got stuck with making nodewatcher run as it used some incompatible / broken deps

**Comment by mitjajez** [comment]
I was not able to build your pr, but I might put some deps too new. I'm now downgrading django 1.11 (latest with python2) -> django 1.7
Or should I restart from your pr?

**Comment by rasovica** [comment]
Its probably best for you to make your own, I am just saying I was going through the same pains and I feel like I got a bit further than you. Maybe you can find some problems already solved on my branch.

**Comment by mitjajez** [comment]
oh, now remember: main problem I found with #7 is db image.
```
Step 3/14 : ADD pgdg.list /etc/apt/sources.list.d/pgdg.list
ERROR: Service 'db' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder251930779/pgdg.list: no such file or directory
```
 That's why I'm trying with `image: tozd/postgresql:9.6` in `docker-compose.yml` [line](https://github.com/mitjajez/mainpage/blob/05037ce56060ae32fa4e2441791b0c4b3c965631/docker-compose.yml#L3)

**Comment by mitjajez** [comment]
I will open new PR with less changes from feature/revive.

**Pull request closed without merging**
